
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: max
  template:
    metadata:
      labels:
        app: max
    spec:
      volumes:
        - name: volume
          hostPath:
            path: /mnt/data
      containers:
        - name: container1-nginx
          image: nginx
          volumeMounts:
            - name: volume
              mountPath: "/var/nginx-data"
        - name: container2-httpd
          image: httpd
          volumeMounts:
            - name: volume
              mountPath: "/var/httpd-data"
