apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: max
  template:
    metadata:
      labels:
        app: max
    spec:
      volumes:
        - name: volume1
          hostPath:
            path: /mnt/data1

        - name: volume2
          hostpath:
             path: /mnt/data2
      containers:
        - name: container1-nginx
          image: nginx
          volumeMounts:
            - name: volume1
              mountPath: "/var/nginx-data"
        - name: container2-httpd
          image: httpd
          volumeMounts:
            - name: volume2
              mountPath: "/var/httpd-data"
