apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: YWRtaW4=   # base64-encoded value of "admin"
  password: c2VjcmV0cGFzc3dvcmQ=   # base64-encoded value of "secretpassword"


## Encode Data to Base64
#echo -n "admin" | base64
#echo -n "secretpassword" | base64
## to decode that
#kubectl get secret my-secret -o jsonpath="{.data.username}" | base64 --decode
