apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-volume-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-volume-app
  template:
    metadata:
      labels:
        app: secret-volume-app
    spec:
      containers:
      - name: mycontainer
        image: madhand249/wesly:latest  # or your image
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secrets"
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: my-secret
