apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: docker_image
    Ports:
    - containerPort: 8080
    env:
    - name: DATABASE_URL
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: database_url
    - name: DATABASE_USER
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: database_user
