apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmap-app
  template:
    metadata:
      labels:
        app: configmap-app
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: my-config
      containers:
      - name: my-container
        image: madhand249/wesly:latest  # Replace with your actual image
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
          readOnly: true
